### ISSUE TITLE
Error message in OBS Studio when importing osc_server.

### ISSUE THREAD

**Issue by MarioMey** [attwad/python-osc#117]
(OBS Studio: [obsproject.com](http://www.obsproject.com)). I think this is not a python-osc bug... but it's strange what's happening.

I installed python-osc and tested examples codes and they work perfectly. But, when importing osc_server inside a OBS script, OBS says:

```
3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
Traceback (most recent call last):
  File "/home/mario/videoconfestejo/obs-scripts/OSCOBS_videoconfestejo.py", line 18, in <module>
    from pythonosc import osc_server
  File "/home/mario/.local/lib/python3.7/site-packages/pythonosc/osc_server.py", line 4, in <module>
    import asyncio
  File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
    from . import events
  File "/usr/lib/python3.7/asyncio/events.py", line 14, in <module>
    import contextvars
  File "/usr/lib/python3.7/contextvars.py", line 1, in <module>
    from _contextvars import Context, ContextVar, Token, copy_context
ImportError: /usr/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyContext_Type
```

As the first line says (I added print(sys.version)), it is using 3.7.3. The same I have in my computer and the same I run the examples

**Comment by MarioMey** [comment]
This [OBS pull request](https://github.com/obsproject/obs-studio/pull/3335) fixes this issue. I can't make OBS to receive OSC messages with python-osc correctly, but I will post in another issue.
