### ISSUE TITLE
Facing OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by SanderNotenbaert** [attwad/python-osc#142]
Hi! Thanks a lot for creating and maintaining this package!

I'm fairly new to all of this, and I've been facing an error that I've been trying to surpass for longer then I dare to admit. 
Ableton Live (11) runs an instance of Python 3.7.3 internally, that can be used to run python scripts (intended for interaction between hardware devices and the Ableton API), called remote scripts. 
After a lot of trial and error I managed to get python-osc (almost) running inside Ableton by adding the package directly in the project folder (as I can't install the package to Ableton's internal Python instance).
Can't seem to get over this last hurdle however: when trying to start a server (Blocking, Threading or Forking alike) I get an
"OSError: [Errno 48] Address already in use" error:

> 2021-05-30T16:26:36.476575: info: RemoteScriptError: Traceback (most recent call last):
> 
> 2021-05-30T16:26:36.476608: info: RemoteScriptError:   File "/Applications/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/Oxygen_Mod/__init__.py", line 7, in create_instance
> 
> 2021-05-30T16:26:36.476717: info: RemoteScriptError:     
> 2021-05-30T16:26:36.476758: info: RemoteScriptError: return Oxygen_Mod(c_instance)
> 2021-05-30T16:26:36.476775: info: RemoteScriptError: 
> 
> 2021-05-30T16:26:36.476794: info: RemoteScriptError:   File "/Applications/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/Oxygen_Mod/Oxygen_Mod.py", line 18, in __init__
> 
> 2021-05-30T16:26:36.476881: info: RemoteScriptError:     
> 2021-05-30T16:26:36.476920: info: RemoteScriptError: self.start_OSC(IP, port)
> 2021-05-30T16:26:36.476947: info: RemoteScriptError: 
> 
> 2021-05-30T16:26:36.476971: info: RemoteScriptError:   File "/Applications/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/Oxygen_Mod/Oxygen_Mod.py", line 34, in start_OSC
> 
> 2021-05-30T16:26:36.477076: info: RemoteScriptError:     
> 2021-05-30T16:26:36.477101: info: RemoteScriptError: self.server = osc_server.ThreadingOSCUDPServer((IP, port), self.dispatch)
> 2021-05-30T16:26:36.477118: info: RemoteScriptError: 
> 
> 2021-05-30T16:26:36.477148: info: RemoteScriptError:   File "/Applications/Ableton Live 11 Suite.app/Contents/App-Resources/MIDI Remote Scripts/Oxygen_Mod/pythonosc/osc_server.py", line 61, in __init__
> 
> 2021-05-30T16:26:36.477258: info: RemoteScriptError:     
> 2021-05-30T16:26:36.477283: info: RemoteScriptError: super().__init__(server_address, _UDPHandler, bind_and_activate)
> 2021-05-30T16:26:36.477300: info: RemoteScriptError: 
> 
> 2021-05-30T16:26:36.477319: info: RemoteScriptError:   File "output/Live/mac_64_static/Release/python-bundle/Python/lib/socketserver.py", line 452, in __init__
> 
> 2021-05-30T16:26:36.477453: info: RemoteScriptError:   File "output/Live/mac_64_static/Release/python-bundle/Python/lib/socketserver.py", line 466, in server_bind
> 
> 2021-05-30T16:26:36.477560: info: RemoteScriptError: OSError
> 2021-05-30T16:26:36.477593: info: RemoteScriptError: : 
> 2021-05-30T16:26:36.477627: info: RemoteScriptError: [Errno 48] Address already in use

UPDATE: I just found that although the traceback seems to indicate that the error occurs on the `self.server = osc_server.ThreadingOSCUDPServer((IP, port), self.dispatch)` line, the issue seems to stem from the  `self.thread.start()` line. 
If I comment out that line, the script runs without errors (but doesn't receive OSC of course). If I change that line to `self.thread.run()`, it runs correctly but it blocks, causing Ableton to be frozen and unusable. I'm now realising this might be more of an issue with how I'm using threading (although I've seen similar examples using threading around), as I admittedly don't really grasp this yet. If you have any quick pointers on whether I'm doing something wrong here, I'd be happy to hear it, otherwise I'll look into other alternatives to make sure it runs without stalling Ableton. 

Here's a simple code example I'm attempting to run, the extra stuff is what's needed to run it in Ableton:

```python
from __future__ import absolute_import, print_function, unicode_literals  #
import Live
import sys, os
from threading import Thread
from _Framework.ControlSurface import ControlSurface

dir = os.path.dirname(__file__)
sys.path.insert(0, dir + "/")
from pythonosc import dispatcher
from pythonosc import osc_server

IP = "127.0.0.1"
port = 5020


class Oxygen_Mod(ControlSurface):
    def __init__(self, c_instance):

        ControlSurface.__init__(self, c_instance)
        with self.component_guard():
            self.start_OSC(IP, port)

    def print_volume_handler(self, unused_addr, args, volume):
        self.log_message(
            unused_addr,
            volume,
        )

    def start_OSC(self, IP, port):
        self.dispatch = dispatcher.Dispatcher()
        self.dispatch.map("/volume*", self.print_volume_handler, "Volume")
        self.server = osc_server.ThreadingOSCUDPServer((IP, port), self.dispatch)
        self.log_message("Serving on {}".format(self.server.server_address))
        # self.server.serve_forever()
        self.thread = Thread(target=self.server.serve_forever)
        self.thread.setDaemon(True)
        self.thread.start()

    def disconnect(self):
        ControlSurface.disconnect(self)

    def refresh_state(self):
        ControlSurface.refresh_state(self)
```

**Comment by SanderNotenbaert** [comment]
Ok, this seems to simply be due to restrictions in the Ableton Python instance. If anyone ever tries to accomplish something similar with this library in Ableton: server.serve_forever is a no-go in Ableton. You'll have to use regular ticks to call process() concurrently.
Here's an example of how it can be done, using python-osc: https://github.com/ideoforms/AbletonOSC
