### ISSUE TITLE
can't send Chinese

### ISSUE THREAD

**Issue by 1217728619** [attwad/python-osc#158]
i try ro send message to VRChat,but i got error codes.
for example i use "client.send_message("/avatar/parameters/密码正确", 1)" ,but i get "/avatar/parameters/????????????"
i don't know if it's VRChat's fault.

**Comment by DrLuke** [comment]
I think it's more likely to be an issue with VRChat. Maybe you can try sending other unicode strings, for example "äöü" and see if that results in a correct string.

**Comment by 1217728619** [comment]
when i change a parameters named "fly" to true, i will get "/avatar/parameters/fly True". 
That's no problem.VRChat will send the changed parameters by OSC.
but for example when i change a parameters named "眼镜" to true,I got the following error
Exception occurred during processing of request from ('127.0.0.1', 54616)
Traceback (most recent call last):
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\osc_server.py", line 29, in handle
    self.server.dispatcher.call_handlers_for_packet(self.request[0], self.client_address)
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\dispatcher.py", line 183, in call_handlers_for_packet
    packet = osc_packet.OscPacket(data)
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\osc_packet.py", line 65, in __init__
    self._messages = [TimedMessage(now, osc_message.OscMessage(dgram))]
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\osc_message.py", line 23, in __init__
    self._parse_datagram()
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\osc_message.py", line 27, in _parse_datagram
    self._address_regexp, index = osc_types.get_string(self._dgram, 0)
  File "C:\Users\12177\AppData\Local\Programs\Python\Python310\lib\site-packages\pythonosc\parsing\osc_types.py", line 88, in get_string
    return data_str.replace(b'\x00', b'').decode('utf-8'), start_index + offset
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 21: invalid continuation byte
did you know what happened,the file what i run is "python-osc-master\examples\simple_2way.py"
Is there a problem with the string encoding method of VRChat?
at last i tried send "äöü" to vrchat and i got "??????",here are six "?".that's interesting.

**Comment by DrLuke** [comment]
Oh sorry I misunderstood, the address of an osc message can only contain ascii characters, so no chinese unfortunately.

**Comment by 1217728619** [comment]
oh! i'm sorry too. i don't know that about OSC.
