### ISSUE TITLE
Unable to install in python 3

### ISSUE THREAD

**Issue by Pixdigit** [attwad/python-osc#77]
when running `python3 -m pip install -r ./requirements.txt` I get the following error:

```
Collecting pyOSC==0.3.5b5294 (from -r ./requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7c/e4/6abb118cf110813a7922119ed0d53e5fe51c570296785ec2a39f37606d85/pyOSC-0.3.5b-5294.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-by82t4hi/pyOSC/setup.py", line 5, in <module>
        import OSC
      File "/tmp/pip-build-by82t4hi/pyOSC/OSC.py", line 735
        binary = struct.pack('>ll', 0L, 1L)
                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-by82t4hi/pyOSC/
```

**Comment by Pixdigit** [comment]
Note: this works when using python 2.7
My python 3 is 3.6

**Comment by attwad** [comment]
python-osc doesn't support python 2.7, only 3.4 and onwards.

pyOSC is a different package: https://pypi.org/project/pyOSC/, I suggest creating an issue on their tracker.

**Comment by Pixdigit** [comment]
Oh. Sorry for the bother.
